#!/bin/bash

INPUT_PATH=$1
OUTPUT_PATH=$2

INPUT_NAME=$(basename $INPUT_PATH)
OUTPUT_NAME=$(basename $OUTPUT_PATH)

mkdir /tmp/wav2mp3

fluidsynth -F /tmp/wav2mp3/${INPUT_NAME%.*}.wav /usr/share/soundfonts/FluidR3_GM.sf2 $INPUT_PATH
lame /tmp/wav2mp3/${INPUT_NAME%.*}.wav $OUTPUT_PATH

rm -r /tmp/wav2mp3
